version: '3.3'

services:
  lh-service:
    image: buildkite/puppeteer
    volumes:
        - ./src:/app
        - ${GCP_KEY_PATH}:/tmp/keys/gcp-keyfile.json:ro
    restart: always
    working_dir: /app
    command: "node main.js"
    ports:
      - "8080:${PORT:-8080}"
    environment:
        PORT: ${PORT:-8080}
        K_SERVICE: lasso
        K_REVISION: 0
        K_CONFIGURATION: lasso
        BQ_DATASET: lh_results
        BQ_TABLE: psmetrics
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/keys/gcp-keyfile.json